version: '3.3'
services:
  back:
    networks:
      - default
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mm
    depends_on:
      - db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  db:
    networks:
      - default
    restart: always
    image: postgres:15.4-alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mm
networks:
  default:
    driver: bridge
